version: 2

macros:
  - name: cents_to_dollars
    description: This macro converts cents amount to dollars 

    arguments:
      - name: column_name
        description: The column data for which cents needs to be converted to dollars 
      - name: decimal_places
        description: Numbers of places to which it needs to be rounded off 
